hero_image_urls = {
    "Spider-Man Peter": "https://i.imgur.com/rUQCPiU.jpeg",
    "Captain Marvel": "https://i.imgur.com/TJv0XwU.jpeg",
    "Iron Man": "https://i.imgur.com/r0CCd9T.jpeg",
    "Black Panther": "https://i.imgur.com/PbCKZF0.jpeg",
    "She-Hulk": "https://i.imgur.com/XJyC93D.jpeg",
    "Captain America": "https://i.imgur.com/pNCGX11.jpeg",
    "Ms. Marvel": "https://i.imgur.com/6sA7dpm.jpeg",
    "Thor": "https://i.imgur.com/9JV7MkM.jpeg",
    "Black Widow": "https://i.imgur.com/Hk3mhos.jpeg",
    "Doctor Strange": "https://i.imgur.com/oBsPO1l.jpeg",
    "Hulk": "https://i.imgur.com/zC3FqPt.jpeg",
    "Hawkeye": "https://i.imgur.com/pHG8eHM.jpeg",
    "Spider-Woman": "https://i.imgur.com/XGFSCGB.jpeg",
    "Ant-Man": "https://i.imgur.com/fRy4gYE.jpeg",
    "Wasp": "https://i.imgur.com/qUpOKYD.jpeg",
    "Quicksilver": "https://i.imgur.com/R6d5sXF.jpeg",
    "Scarlet Witch": "https://i.imgur.com/PWRHJI5.jpeg",
    "Groot": "https://i.imgur.com/b8jo7qL.jpeg",
    "Rocket": "https://i.imgur.com/qzBttPC.jpeg",
    "Star-Lord": "https://i.imgur.com/OqKpZvi.jpeg",
    "Gamora": "https://i.imgur.com/4yKLqEK.jpeg",
    "Drax": "https://i.imgur.com/HlC4xkL.jpeg",
    "Venom (Flash)": "https://i.imgur.com/cs77kT6.jpeg",
    "Spectrum": "https://i.imgur.com/7MD5bX7.jpeg",
    "Adam Warlock": "https://i.imgur.com/jXqA4vR.jpeg",
    "Nebula": "https://i.imgur.com/sDqKlRD.jpeg",
    "War Machine": "https://i.imgur.com/DdwS6fC.jpeg",
    "Valkyrie": "https://i.imgur.com/6PJpQic.jpeg",
    "Vision": "https://i.imgur.com/EBfS6yg.jpeg",
    "Ghost Spider": "https://i.imgur.com/2GEyrsW.jpeg",
    "Spider-Man (Miles)": "https://i.imgur.com/QUXyFIH.jpeg",
    "Nova": "https://i.imgur.com/IKXQlNM.jpeg",
    "Ironheart": "https://i.imgur.com/5HhKJv5.jpeg",
    "SP//dr": "https://i.imgur.com/hWf0S7s.jpeg",
    "Spider-Ham": "https://i.imgur.com/bIigd7R.jpeg",
    "Colossus": "https://i.imgur.com/E7GHo5B.jpeg",
    "Cyclops": "https://i.imgur.com/KEifLjf.jpeg",
    "Shadowcat": "https://i.imgur.com/gUDyBwx.jpeg",
    "Phoenix": "https://i.imgur.com/egDlUEK.jpeg",
    "Wolverine": "https://i.imgur.com/XBs6W2O.jpeg",
    "Storm": "https://i.imgur.com/FHXnyBN.jpeg",
    "Gambit": "https://i.imgur.com/t1fI34N.jpeg",
    "Rogue": "https://i.imgur.com/eXtPWzs.jpeg",
    "Cable": "https://i.imgur.com/JuTvG4a.jpeg",
    "Domino": "https://i.imgur.com/AuGqACj.jpeg",
    "Psylocke": "https://i.imgur.com/mvUX7es.jpeg",
    "Angel": "https://i.imgur.com/vutfimf.jpeg",
    "X-23": "https://i.imgur.com/XGrOdRt.jpeg",
    "Deadpool": "https://i.imgur.com/VKttFit.jpeg",
    "Bishop": "https://i.imgur.com/MFPhsfd.jpeg",
    "Magik": "https://i.imgur.com/zvQvAWw.jpeg",
    "Iceman": "https://i.imgur.com/Zz8fckB.jpeg",
    "Jubilee": "https://i.imgur.com/i1I8kF8.jpeg",
    "Nightcrawler": "https://i.imgur.com/5zk1bjK.jpeg",
    "Magneto": "https://i.imgur.com/xN6Kfdv.jpeg",
    "Maria Hill": "https://i.imgur.com/DpffPA9.jpeg",
    "Nick Fury": "https://i.imgur.com/6STdIKk.jpeg",
    "Shuri": "https://i.imgur.com/CdLOKBd.jpeg",
    "Silk": "https://i.imgur.com/UCmYWV8.jpeg",
}